# Generated by Django 3.2.14 on 2022-07-28 01:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id_product', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('responsible', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('content', models.CharField(max_length=255)),
                ('creation', models.DateField(auto_now_add=True)),
                ('price', models.FloatField()),
            ],
        ),
    ]
