# Generated by Django 4.0.6 on 2022-08-05 08:27

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20220803_2206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=products.models.upload_image_products),
        ),
    ]
